@base = http://localhost:8000
###
GET {{base}} HTTP/1.1
###
PUT {{base}}/1 HTTP/1.1
Content-Type: application/json

{"name": "Green Tea", "price": 10.90, "SKU": "abc-def-ghi"}
###
POST {{base}} HTTP/1.1
Content-Type: application/json

{"name":"Water",  "price": 5.90, "SKU": "zyx-wvu-tsr"}
###
GET {{base}}/1 HTTP/1.1
###
DELETE {{base}}/2 HTTP/1.1
###
GET {{base}}/docs HTTP/1.1